// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ListenKey } from '../../nanokv/packet/listen-key.js';


export class Listen {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Listen {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsListen(bb:flatbuffers.ByteBuffer, obj?:Listen):Listen {
  return (obj || new Listen()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsListen(bb:flatbuffers.ByteBuffer, obj?:Listen):Listen {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Listen()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

added(index: number, obj?:ListenKey):ListenKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new ListenKey()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

addedLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

removed(index: number, obj?:ListenKey):ListenKey|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ListenKey()).__init(this.bb!.__indirect(this.bb!.__vector(this.bb_pos + offset) + index * 4), this.bb!) : null;
}

removedLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startListen(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addAdded(builder:flatbuffers.Builder, addedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, addedOffset, 0);
}

static createAddedVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startAddedVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static addRemoved(builder:flatbuffers.Builder, removedOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, removedOffset, 0);
}

static createRemovedVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startRemovedVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endListen(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createListen(builder:flatbuffers.Builder, addedOffset:flatbuffers.Offset, removedOffset:flatbuffers.Offset):flatbuffers.Offset {
  Listen.startListen(builder);
  Listen.addAdded(builder, addedOffset);
  Listen.addRemoved(builder, removedOffset);
  return Listen.endListen(builder);
}
}
