// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export { QueueValueHolder } from './internal/queue-value-holder.js';
export { ValueHolder } from './internal/value-holder.js';
