// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum ValueEncoding {
  BYTES = 0,
  SERIALIZED = 1,
  LE64 = 2
}
