// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ValueEncoding } from '../../nanokv/shared/value-encoding.js';


export class QueueValueHolder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):QueueValueHolder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsQueueValueHolder(bb:flatbuffers.ByteBuffer, obj?:QueueValueHolder):QueueValueHolder {
  return (obj || new QueueValueHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsQueueValueHolder(bb:flatbuffers.ByteBuffer, obj?:QueueValueHolder):QueueValueHolder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new QueueValueHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

encoding():ValueEncoding {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ValueEncoding.BYTES;
}

static startQueueValueHolder(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addEncoding(builder:flatbuffers.Builder, encoding:ValueEncoding) {
  builder.addFieldInt8(1, encoding, ValueEncoding.BYTES);
}

static endQueueValueHolder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createQueueValueHolder(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset, encoding:ValueEncoding):flatbuffers.Offset {
  QueueValueHolder.startQueueValueHolder(builder);
  QueueValueHolder.addValue(builder, valueOffset);
  QueueValueHolder.addEncoding(builder, encoding);
  return QueueValueHolder.endQueueValueHolder(builder);
}
}
