// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ValueEncoding } from '../../nanokv/shared/value-encoding.js';


export class ValueHolder {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ValueHolder {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsValueHolder(bb:flatbuffers.ByteBuffer, obj?:ValueHolder):ValueHolder {
  return (obj || new ValueHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsValueHolder(bb:flatbuffers.ByteBuffer, obj?:ValueHolder):ValueHolder {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ValueHolder()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

value(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

encoding():ValueEncoding {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ValueEncoding.BYTES;
}

version():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

expiredAt():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

static startValueHolder(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addEncoding(builder:flatbuffers.Builder, encoding:ValueEncoding) {
  builder.addFieldInt8(1, encoding, ValueEncoding.BYTES);
}

static addVersion(builder:flatbuffers.Builder, version:bigint) {
  builder.addFieldInt64(2, version, BigInt('0'));
}

static addExpiredAt(builder:flatbuffers.Builder, expiredAt:bigint) {
  builder.addFieldInt64(3, expiredAt, BigInt('0'));
}

static endValueHolder(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createValueHolder(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset, encoding:ValueEncoding, version:bigint, expiredAt:bigint):flatbuffers.Offset {
  ValueHolder.startValueHolder(builder);
  ValueHolder.addValue(builder, valueOffset);
  ValueHolder.addEncoding(builder, encoding);
  ValueHolder.addVersion(builder, version);
  ValueHolder.addExpiredAt(builder, expiredAt);
  return ValueHolder.endValueHolder(builder);
}
}
