// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ValueEncoding } from '../../nanokv/shared/value-encoding.js';


export class ValueHeader {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ValueHeader {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsValueHeader(bb:flatbuffers.ByteBuffer, obj?:ValueHeader):ValueHeader {
  return (obj || new ValueHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsValueHeader(bb:flatbuffers.ByteBuffer, obj?:ValueHeader):ValueHeader {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ValueHeader()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

version():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

encoding():ValueEncoding {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ValueEncoding.BYTES;
}

value(index: number):number|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : 0;
}

valueLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

valueArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startValueHeader(builder:flatbuffers.Builder) {
  builder.startObject(3);
}

static addVersion(builder:flatbuffers.Builder, version:bigint) {
  builder.addFieldInt64(0, version, BigInt('0'));
}

static addEncoding(builder:flatbuffers.Builder, encoding:ValueEncoding) {
  builder.addFieldInt8(1, encoding, ValueEncoding.BYTES);
}

static addValue(builder:flatbuffers.Builder, valueOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, valueOffset, 0);
}

static createValueVector(builder:flatbuffers.Builder, data:number[]|Uint8Array):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startValueVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endValueHeader(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createValueHeader(builder:flatbuffers.Builder, version:bigint, encoding:ValueEncoding, valueOffset:flatbuffers.Offset):flatbuffers.Offset {
  ValueHeader.startValueHeader(builder);
  ValueHeader.addVersion(builder, version);
  ValueHeader.addEncoding(builder, encoding);
  ValueHeader.addValue(builder, valueOffset);
  return ValueHeader.endValueHeader(builder);
}
}
