name: typedoc
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: ["🍀"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
      - run: bun install
        working-directory: ./npm/nanokv
      - run: bun x typedoc index.ts type_helpers.ts --out ../docs
        working-directory: ./npm/nanokv
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./npm/docs
  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
